version: '3'
services:
  app:
    image: duplicatebooru
    build:
      context: .
    ports:
    - '8080:8080'
    volumes:
    - '.:/app'
    environment:
      PYTHONASYNCIODEBUG: "1"
  redis:
    image: redis:6
